# Generated by Django 6.0.6 on 2026-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional — international format e.g. +1 555 234 5678', max_length=30),
        ),
    ]
